import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="p-4 flex gap-10 bg-cyan-900 rounded-2xl mb-8">
          <Link href='/'>Home</Link>
          <Link href='/about'>About</Link>
          <Link href='/nextPeriod'>Next Period</Link>
          <Link href='/nextPeriod/nextSubject'>Next Subject</Link>
        </nav>
      <div className="border border-red-400 p-6 rounded-2xl ">
        {children}
      </div>
      </body>
    </html>
  );
}
